test2428

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -68,45 +68,68 @@ jobs:
 #            GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}  # Needed to get PR information, if any
 #            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  sonarQube:
+#  sonarQube:
+#    runs-on: ubuntu-latest
+#
+#    services:
+#      sonarqube:
+#        image: sonarqube:latest
+#        ports:
+#          - 9000:9000
+#        options: --health-cmd="curl -f http://localhost:9000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '17'
+#          distribution: 'temurin'
+#
+#      - name: Wait for SonarQube to be ready
+#        run: |
+#          echo "Waiting for SonarQube to be ready..."
+#          timeout 60 bash -c 'until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do sleep 5; done'
+#
+#      - name: Download SonarScanner compatible with Java 17
+#        run: |
+#          # Download the SonarScanner version that does not bundle its own JRE
+#          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
+#          unzip sonar-scanner.zip -d $HOME/sonar-scanner
+#          echo "$HOME/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH
+#
+#      - name: Run SonarQube Scanner
+#        env:
+#          SONAR_HOST_URL: http://localhost:9000
+#          SONAR_TOKEN: ${{ secrets.DMS_TKN }}
+#        run: |
+#          sonar-scanner
+
+  sonarQubeScan1:
+    name: sonarQubeScan1
     runs-on: ubuntu-latest
 
-    services:
-      sonarqube:
-        image: sonarqube:latest
-        ports:
-          - 9000:9000
-        options: --health-cmd="curl -f http://localhost:9000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries=5
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/checkout@v4
         with:
-          java-version: '17'
-          distribution: 'temurin'
-
-      - name: Wait for SonarQube to be ready
-        run: |
-          echo "Waiting for SonarQube to be ready..."
-          timeout 60 bash -c 'until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do sleep 5; done'
-
-      - name: Download SonarScanner compatible with Java 17
-        run: |
-          # Download the SonarScanner version that does not bundle its own JRE
-          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
-          unzip sonar-scanner.zip -d $HOME/sonar-scanner
-          echo "$HOME/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH
-
-      - name: Run SonarQube Scanner
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - name: SonarQube Scan 1
+        uses: sonarsource/sonarqube-scan-action@master
         env:
-          SONAR_HOST_URL: http://localhost:9000
-          SONAR_TOKEN: ${{ secrets.DMS_TKN }}
-        run: |
-          sonar-scanner
-
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_1 }}  # analysis token associated to your project
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        with:
+          projectBaseDir: PROJECT1_PATH/ # the path to your project from the monorepo root directory
+      # If you wish to fail your job when the Quality Gate is red, uncomment the
+      # following lines. This would typically be used to fail a deployment.
+      # We do not recommend to use this in a pull request. Prefer using pull request
+      # decoration instead.
+      # - uses: sonarsource/sonarqube-quality-gate-action@master
+      #   timeout-minutes: 5
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_1 }}
 
 
 
